\section{Conclusion}
In this piece, we introduce a flexible method to account for spatial imprecison in datasets for the purpose of fitting models in the case of spatial imprecision in measurements - geoSIMEX.
We illustrate the relative accuracy of geoSIMEX as contrasted to other methods which do not account for spatial imprecision, finding that geoSIMEX outperforms all other tested approaches, though at the tradeoff of a lower ability to identify statistical significance in relationships.
Additionally, as an illustrative example we applied geoSIMEX to the case of Chinese aid's impact on NDVI in Southeast Asia.  
In models which did not account for spatial imprecision, it was found that Chinese aid had a statistically significant, detrimental impact on forest cover.
By accounting for spatial imprecision, we illustrated that there was insufficient evidence to draw this conclusion.
We use these findings to argue for the importance of incorporating spatial imprecision into analyses.
Finally, we introduce the geo(query) software - with which all data used in this analysis can be retrieved - as well as an accompanying R package - geoSIMEX - for users seeking to incorporate information on spatial imprecision into analyses.